theme = {}

theme.font          = "terminus 8"

theme.bg_normal     = "#222222"
theme.bg_focus      = "#535d6c"
theme.bg_urgent     = "#ff0000"
theme.bg_minimize   = "#444444"
theme.fg_normal     = "#aaaaaa"
theme.fg_focus      = "#ffffff"
theme.fg_urgent     = "#ffffff"
theme.fg_minimize   = "#ffffff"
theme.border_width  = "1"
theme.border_normal = "#000000"
theme.border_focus  = "#535d6c"
theme.border_marked = "#91231c"

theme.taglist_squares_sel   = "/home/s7ang3r/.config/awesome/taglist/squarefw.png"
theme.taglist_squares_unsel = "/home/s7ang3r/.config/awesome/taglist/squarew.png"
theme.tasklist_floating_icon = "/home/s7ang3r/.config/awesome/tasklist/floatingw.png"

theme.menu_submenu_icon = "/home/s7ang3r/.config/awesome/submenu.png"
theme.menu_height = "15"
theme.menu_width  = "100"

theme.titlebar_close_button_normal = "/home/s7ang3r/.config/awesome/titlebar/close_normal.png"
theme.titlebar_close_button_focus  = "/home/s7ang3r/.config/awesome/titlebar/close_focus.png"
theme.titlebar_ontop_button_normal_inactive = "/home/s7ang3r/.config/awesome/titlebar/ontop_normal_inactive.png"
theme.titlebar_ontop_button_focus_inactive  = "/home/s7ang3r/.config/awesome/titlebar/ontop_focus_inactive.png"
theme.titlebar_ontop_button_normal_active = "/home/s7ang3r/.config/awesome/titlebar/ontop_normal_active.png"
theme.titlebar_ontop_button_focus_active  = "/home/s7ang3r/.config/awesome/titlebar/ontop_focus_active.png"
theme.titlebar_sticky_button_normal_inactive = "/home/s7ang3r/.config/awesome/titlebar/sticky_normal_inactive.png"
theme.titlebar_sticky_button_focus_inactive  = "/home/s7ang3r/.config/awesome/titlebar/sticky_focus_inactive.png"
theme.titlebar_sticky_button_normal_active = "/home/s7ang3r/.config/awesome/titlebar/sticky_normal_active.png"
theme.titlebar_sticky_button_focus_active  = "/home/s7ang3r/.config/awesome/titlebar/sticky_focus_active.png"
theme.titlebar_floating_button_normal_inactive = "/home/s7ang3r/.config/awesome/titlebar/floating_normal_inactive.png"
theme.titlebar_floating_button_focus_inactive  = "/home/s7ang3r/.config/awesome/titlebar/floating_focus_inactive.png"
theme.titlebar_floating_button_normal_active = "/home/s7ang3r/.config/awesome/titlebar/floating_normal_active.png"
theme.titlebar_floating_button_focus_active  = "/home/s7ang3r/.config/awesome/titlebar/floating_focus_active.png"
theme.titlebar_maximized_button_normal_inactive = "/home/s7ang3r/.config/awesome/titlebar/maximized_normal_inactive.png"
theme.titlebar_maximized_button_focus_inactive  = "/home/s7ang3r/.config/awesome/titlebar/maximized_focus_inactive.png"
theme.titlebar_maximized_button_normal_active = "/home/s7ang3r/.config/awesome/titlebar/maximized_normal_active.png"
theme.titlebar_maximized_button_focus_active  = "/home/s7ang3r/.config/awesome/titlebar/maximized_focus_active.png"

